### Vector Multiplication

In [1]:
import numpy as np

In [2]:
w = np.random.rand(1,6)
w

array([[0.59079059, 0.9551018 , 0.27175603, 0.95998699, 0.80005197,
        0.37415292]])

In [3]:
w.shape

(1, 6)

In [4]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])


In [5]:
v.shape

(4,)

In [6]:
def vector_vector_multiplication(x,y):
    assert x.shape[0] == y.shape[0]

    n  = x.shape[0]

    result = 0.0

    for i in range(n):
        result = result + (x[i] * y[i])
    return result

In [7]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [8]:
u.dot(v)

np.int64(110)

### Matrix Vector Multiplication

In [9]:
U = np.random.randint(100,size=(3,4)) # Random array
U

array([[52, 42, 19,  3],
       [ 8,  9, 39, 18],
       [79, 90, 60, 69]])

In [10]:
U.shape

(3, 4)

In [11]:
v = np.random.randint(100,size=(4))
v

array([67, 61, 73, 59])

In [12]:
v.shape

(4,)

In [27]:
V = np.random.randint(100,size=(4,4))
V

array([[29, 49, 66, 66],
       [79, 42, 32, 22],
       [13, 89, 68, 49],
       [55, 84, 88, 60]])

In [13]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    n_rows = U.shape[0]

    result = np.zeros(n_rows)

    for i in range(n_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result


In [16]:
matrix_vector_multiplication(U,v)

array([ 7610.,  4994., 19234.])

### Matrix - Matrix Multiplication

In [28]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows,num_cols))

    for i in range(num_rows):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)

        result[:,i] = Uvi
    return result 

In [29]:
matrix_matrix_multiplication(U,V)

array([[ 5238.,  6255.,  6332.,     0.],
       [ 2440.,  5753.,  5052.,     0.],
       [13976., 18787., 18246.,     0.]])

## Identity Matrix

In [35]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
V

array([[29, 49, 66, 66],
       [79, 42, 32, 22],
       [13, 89, 68, 49],
       [55, 84, 88, 60]])

In [36]:
V.dot(I)

array([[29., 49., 66., 66.],
       [79., 42., 32., 22.],
       [13., 89., 68., 49.],
       [55., 84., 88., 60.]])

## Inverse

In [46]:
Vs = V[[0,1,2,3]]
Vs

array([[29, 49, 66, 66],
       [79, 42, 32, 22],
       [13, 89, 68, 49],
       [55, 84, 88, 60]])

In [47]:
Vs_inverse = np.linalg.inv(Vs)
Vs_inverse

array([[ 0.00066403,  0.01396095, -0.00625215, -0.00074352],
       [-0.00413848,  0.01510254,  0.0319236 , -0.02705621],
       [-0.02731515, -0.03555909, -0.03858901,  0.07459936],
       [ 0.04524741,  0.01821225,  0.01763531, -0.05418548]])

In [48]:
Vs_inverse.dot(Vs)

array([[ 1.00000000e+00, -5.46437895e-17, -8.50014503e-17,
        -7.37257477e-17],
       [-1.00613962e-16,  1.00000000e+00,  1.94289029e-16,
         3.74700271e-16],
       [ 5.96744876e-16, -8.32667268e-16,  1.00000000e+00,
        -7.21644966e-16],
       [-3.60822483e-16,  1.11022302e-16, -2.22044605e-16,
         1.00000000e+00]])