In [1]:
%pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 104.6 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


## Machine Learning

- Creating arrays
- Multi dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operators
    - Logical operators
- Summarizing operations

In [2]:
import numpy as np

### Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,4.6)

array([4.6, 4.6, 4.6, 4.6, 4.6, 4.6, 4.6, 4.6, 4.6, 4.6])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

### Multi-dimensional array

In [10]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
n = np.array([
    [1,2,3],
    [4,5,3],
    [7,8,9],
]) 

# Row then Column

n[0,1] 

np.int64(2)

In [18]:
#return rows
n[0]

array([1, 2, 3])

In [21]:
# return columns - returns all rows and col at index 2
n[:,2]

array([3, 3, 9])

In [22]:
n[:,2] = [35,67,4.5]

In [23]:
n

array([[ 1,  2, 35],
       [ 4,  5, 67],
       [ 7,  8,  4]])

### Randomly Generated Arrays

In [27]:
np.random.rand(5,2) # Random array

array([[0.45611178, 0.07380384],
       [0.57439738, 0.93315124],
       [0.44900975, 0.87613835],
       [0.48698821, 0.77218356],
       [0.62339318, 0.27322804]])

In [30]:
np.random.seed(2)
np.random.rand(5,2) # Random array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
# np.random.randn - Samples from normal distribution
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

### Element wise Operations



In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a*100

array([  0, 100, 200, 300, 400])

In [35]:
b = (10+(a/10)) **2 /100
b

array([1.    , 1.0201, 1.0404, 1.0609, 1.0816])

In [36]:
a/b + 10

array([10.        , 10.98029605, 11.92233756, 12.82778773, 13.69822485])

### Comparison Operators

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a > 2

array([False, False, False,  True,  True])

In [39]:
b

array([1.    , 1.0201, 1.0404, 1.0609, 1.0816])

In [40]:
a > b

array([False, False,  True,  True,  True])

In [42]:
a[a>b]
# returns elements of A for which the condition is true

array([2, 3, 4])

### Summarizing Operators

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(4)

In [45]:
a.mean()

np.float64(2.0)