### Vector Multiplication

In [1]:
import numpy as np

In [11]:
w = np.random.rand(1,6)
w

array([[0.33783302, 0.54643789, 0.81223628, 0.763873  , 0.49262211,
        0.86954196]])

In [12]:
w.shape

(1, 6)

In [4]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])


In [13]:
v.shape

(4,)

In [16]:
def vector_vector_multiplication(x,y):
    assert x.shape[0] == y.shape[0]

    n  = x.shape[0]

    result = 0.0

    for i in range(n):
        result = result + (x[i] * y[i])
    return result

In [17]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [18]:
u.dot(v)

np.int64(110)

### Matrix Vector Multiplication

In [31]:
U = np.random.randint(100,size=(3,4)) # Random array
U

array([[10, 67, 48, 35],
       [35,  8, 52, 71],
       [ 3, 72,  7, 98]])

In [32]:
U.shape

(3, 4)

In [33]:
v = np.random.randint(100,size=(4))
v

array([34, 94, 64, 94])

In [30]:
v.shape

(4,)

In [36]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    n_rows = U.shape[0]

    result = np.zeros(n_rows)

    for i in range(n_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result


In [37]:
matrix_vector_multiplication(U,v)

array([13000., 11944., 16530.])